
import { Task } from '../types';

const formatToICSDate = (isoString: string): string => {
  const date = new Date(isoString);
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
};

export const generateGoogleCalendarUrl = (task: Task): string => {
  const start = formatToICSDate(task.startTime);
  const end = formatToICSDate(task.endTime);
  const details = encodeURIComponent(`${task.notes || ''}\n\nGenerated by Flowmind`);
  const title = encodeURIComponent(task.title);

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${start}/${end}&details=${details}`;
};

export const generateOutlookCalendarUrl = (task: Task): string => {
  const start = new Date(task.startTime).toISOString();
  const end = new Date(task.endTime).toISOString();
  const details = encodeURIComponent(`${task.notes || ''}\n\nGenerated by Flowmind`);
  const title = encodeURIComponent(task.title);

  return `https://outlook.live.com/calendar/0/deeplink/compose?subject=${title}&startdt=${start}&enddt=${end}&body=${details}`;
};

export const generateICSFile = (task: Task): void => {
  const start = formatToICSDate(task.startTime);
  const end = formatToICSDate(task.endTime);
  const now = formatToICSDate(new Date().toISOString());

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Flowmind//Task Planner//ID',
    'BEGIN:VEVENT',
    `UID:${task.id}@flowmind.app`,
    `DTSTAMP:${now}`,
    `DTSTART:${start}`,
    `DTEND:${end}`,
    `SUMMARY:${task.title}`,
    `DESCRIPTION:${(task.notes || '').replace(/\n/g, '\\n')}\\n\\nGenerated by Flowmind`,
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n');

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${task.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
